# Ignore everything
**

# But include the necessary parts
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc
!/apps/frontend
!/libs/payload-types
!/libs/rich-text

# These should be ignored, though
**/.next
**/.react-router
**/build
**/coverage
**/playwright-report
**/storybook-static
**/.cache
**/node_modules
**/tests
**/.env*
**/tsconfig.tsbuildinfo
**/*.log
**/.vscode
**/.DS_Store
